import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/layout/nav/Nav";
import Footer from "@/components/layout/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
