import "./globals.css";
import { Inter, Lato, Playfair_Display } from "next/font/google";
import Nav from "@/components/layout/nav/Nav";
import Footer from "@/components/layout/footer/Footer";
import SessionProvider  from "./Providers";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ subsets: ["latin"], weight: ["700", "400"] });
const play = Playfair_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Digital Harbor",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={lato.className}>
          <Nav />
          {children}
          <Footer />
        </body>
      </SessionProvider>
    </html>
  );
}
