import Login from "@/components/auth/Login";
import Title from "@/components/utils/Title";
import React from "react";
import Link from "next/link";
import { FaArrowLeftLong } from "react-icons/fa6";

export const metadata = {
  title: "Login - Digital harbour",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return (
    <section className="w-full flex flex-col items-center py-5">
      <div className="w-96">
        <Link href="/" className="flex items-center gap-2">
          <FaArrowLeftLong />
          Back to home
        </Link>
        <Title title="Login to your account" />
      </div>
      <Login />
    </section>
  );
};

export default LoginPage;
