# Generated by Django 5.0 on 2023-12-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
