# Generated by Django 5.0 on 2023-12-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_brand_date_created_category_date_created_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
