# Generated by Django 5.0 on 2023-12-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_productimage_product_date_added_product_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_images",
            field=models.ManyToManyField(blank=True, null=True, to="base.productimage"),
        ),
    ]
