# Generated by Django 5.0 on 2023-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_productimage_product_productimage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="brand",
            field=models.CharField(
                max_length=225, unique=True, verbose_name="Brand name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(
                max_length=225, unique=True, verbose_name="Product Category"
            ),
        ),
    ]
