# Generated by Django 4.2 on 2024-01-05 16:59

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_product_color_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="brand_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.models.upload_folder,
                verbose_name="Brand Image",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="category_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.models.upload_folder,
                verbose_name="Category Image",
            ),
        ),
    ]
