import Register from "@/components/auth/Register";
import Title from "@/components/utils/Title";
import Link from "next/link";
import React from "react";
import { FaArrowLeftLong } from "react-icons/fa6";

export const metadata = {
  title: "Signup - Digital harbour",
  description: "Generated by create next app",
};

export default function SignUp() {
  return (
    <section className="w-full flex flex-col items-center py-5">
      <div className="w-96">
        <Link href="/" className="flex items-center gap-2">
          <FaArrowLeftLong />
          Back to home
        </Link>
        <Title title="Create an account today" />
      </div>
      <Register />
    </section>
  );
}
